version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      jenkins-network:
        ipv4_address: 172.21.0.2

  jenkins-agent:
    image: jenkins-agent-image:latest
    container_name: jenkins-agent
    ports:
      - "22:22"
    volumes:
        - agent_data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      jenkins-network:
        ipv4_address: 172.21.0.3

networks:
  jenkins-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  jenkins_home:
    external: true
  agent_data: